pipeline {
    agent {
        docker {
            image 'maven:3.9.2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package -Dmaven.repo.local=$WORKSPACE/.m2/repository'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test -Dmaven.repo.local=$WORKSPACE/.m2/repository'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
