name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run versioning script
        run: ./version.sh

      - name: Build JAR with Maven
        run: mvn clean package

      - name: Build Docker image
        run: |
          docker build -t your-docker-username/simple-java-maven-app:latest .
          docker tag your-docker-username/simple-java-maven-app:latest your-docker-username/simple-java-maven-app:$(cat version.txt)

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: |
          docker push your-docker-username/simple-java-maven-app:latest
          docker push your-docker-username/simple-java-maven-app:$(cat version.txt)

